#!/bin/bash

gl_dstIP=host.docker.internal
gl_dstUser=$(id -un)
gl_sshKey=${HOME}/.ssh/id_rsa

echo "$(date) -- $0 $@" >> ${HOME}/vbox.log
gl_progName="${0##*/}"

gl_args=( "$@" )
gl_args=( "${gl_args[@]/#/\\\"}" )
gl_args=( "${gl_args[@]/%/\\\"}" )

eval "ssh -i ${gl_sshKey} ${gl_dstUser}@${gl_dstIP} bash -lc \"${gl_progName} ${gl_args[@]}\""
gl_exitcode=$?
echo "${gl_exitcode}" >> ${HOME}/vbox.log
exit ${gl_exitcode}
